# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource:
        path: ../src/Controller/        # Où sont les contrôleurs
        namespace: App\Controller
    type: attribute                     # On utilise les attributs PHP (#[Route])
    prefix: /{_locale}                  # TOUTES les routes auront /{_locale} devant
    requirements:
        _locale: fr|en                  # La locale peut être 'fr' OU 'en' uniquement
    defaults:
        _locale: fr